# Generated by Django 5.1.3 on 2024-11-08 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("habit", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="habits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец привычки",
            ),
        ),
        migrations.AddField(
            model_name="reward",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rewards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец вознаграждения",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="reward",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habits",
                to="habit.reward",
                verbose_name="Вознаграждение",
            ),
        ),
    ]
