# Generated by Django 5.1.3 on 2024-11-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0003_remove_condition_minutes_to_complete_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habit",
            options={
                "ordering": ("name",),
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.AlterField(
            model_name="condition",
            name="number_of_repetitions",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Количество повторений"
            ),
        ),
        migrations.AlterField(
            model_name="condition",
            name="place",
            field=models.CharField(max_length=150, verbose_name="Место выполнения"),
        ),
    ]
