# Generated by Django 5.1.3 on 2024-11-17 13:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habit", "0007_rename_last_send_habit_next_sending"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MaxValueValidator(7),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Периодичность выполнения в днях",
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="next_sending",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Дата следующей отправки уведомления в Telegram",
            ),
        ),
    ]
